Add stats process group and uptime plot client

diff --git a/support/contrib/uptime-plot/setup b/support/contrib/uptime-plot/setup
--- a/support/contrib/uptime-plot/setup
+++ b/support/contrib/uptime-plot/setup
@@ -1,23 +1,31 @@
 #!/bin/sh
 
-set -o errexit
+set -o errexit  # abort on nonzero exitstatus
+set -o nounset  # abort on unbound variable
+set -o pipefail # do not hide errors within pipes
 
-export PATH=$PATH:/opt/transport/groups/mango/support/bin
-export PATH=$PATH:/opt/python-3.11.2/bin
+PROJECT=uptime-plot
 
-echo "Creating summary CSV file"
-uptime_summary.sh -o uptime.csv
+SCRIPTDIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null 2>&1 && pwd )"
+BASEDIR=$(realpath $SCRIPTDIR/../..)
 
-echo "Creating virtual env"
-if [ -d venv ]; then 
-    rm -rf venv; 
-fi
+PROJECT_CONTRIB=$BASEDIR/contrib/$PROJECT
+PROJECT_VAR=$BASEDIR/var/$PROJECT
+VENV=$PROJECT_VAR/venv
 
-python3.11 -m venv venv
-. venv/bin/activate
+: ${PYTHON:=python3}
+
+mkdir -p $PROJECT_VAR
+
+rm -rf $VENV
+
+echo "PYTHON=$PYTHON"
+echo "Installing into $VENV"
+
+$PYTHON -m venv $VENV 
+. $VENV/bin/activate
 
 pip install -U pip
-
-pip install -r requirements.txt
+pip install -r $PROJECT_CONTRIB/requirements.txt
 
 
